name: Generate manifest.json

on:
  push:
    branches: [ main ]
    paths:
      - 'images/**'        # only run when image files change
      - '.github/workflows/generate-manifest.yml'

permissions:
  contents: write

jobs:
  generate-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate manifest.json
        run: |
          echo "Generating manifest.json..."
          python3 <<'EOF'
          import os, json

          root = "images"
          manifest = {}

          for dirpath, _, files in os.walk(root):
              images = [os.path.join(dirpath, f).replace("\\", "/")
                        for f in files
                        if f.lower().endswith((".jpg", ".jpeg", ".png", ".gif", ".webp"))]
              if images:
                  key = os.path.relpath(dirpath, root)
                  manifest[key if key != "." else "root"] = images

          with open("manifest.json", "w", encoding="utf-8") as f:
              json.dump(manifest, f, indent=2)
          EOF

      - name: Commit and push manifest
        run: |
          if [ -n "$(git status --porcelain manifest.json)" ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add manifest.json
            git commit -m "Update manifest.json"
            git push
          else
            echo "No changes in manifest.json"
          fi
